### PR TITLE
Jest config

### PR DESCRIPTION
**Pull request by bradsk88**
This should get you moving again.

The tests are still failing because of `VideoDetails` fairly heavy-handed constructor.

I see that you replaced `UUID` with `VideoDetails`.  I would actually recommend not passing `VideoDetails` around until it is absolutely necessary.  Because, it's a fairly bloated object and the recommender only needs a small set of values from it.  YAGNI, etc.

### CODE REVIEW

**Comment by Jorropo** [comment]
Thx 😉

In fact I use videodetails cause this function require videodetails (why not only uuid ?) Cause only uuid don't allow me to access to the tags, a solution could be to pass in args tag + uuid and I think I will do that (and that will maybe be faster in execution time)

**Comment by bradsk88** [comment]
Oops.  Looks like I forgot one thing.  Hang on a sec before merging this.

**Comment by Jorropo** [comment]
Oups, one second to late (I will revert and drop this commit)

**Comment by bradsk88** [comment]
You can just run `yarn add -D @babel/plugin-transform-modules-commonjs`

**Comment by Jorropo** [comment]
Ok, thx, I haven't access to a computer right now, but I will do that not so late.

**Comment by bradsk88** [comment]
https://github.com/Jorropo/PeerTube/pull/8

**Pull request merged**
